;; Various helper functions that unfuck emacs default behavior
(defun kill-word-without-fucking-up-the-clipboard (_)
  (interactive "p")
  (delete-region
   (point)
   (progn
     (forward-word)
     (point))))

(defun backward-kill-word-without-fucking-up-the-clipboard (_)
  (interactive "p")
  (delete-region
   (point)
   (progn
     (forward-word -1)
     (point))))

(defun kill-whole-line-without-fucking-up-the-clipboard ()
  (interactive)
  (let (p1 p2)
    (beginning-of-line)
    (setq p1 (point))
    (end-of-line)
    (setq p2 (point))
    (delete-region p1 p2)
    (delete-char 1)))

(defun execute-region-contents-as-shell-command-and-print-output (start end)
  (interactive "r")
  (let (input output))
  (if (use-region-p)
      (progn
        (setq input (buffer-substring start end))
        (delete-region start end)
        (setq output (shell-command-to-string input))
        (insert output))))

;; Unbind
(unbind-key "C-x o")
(unbind-key "C-_")
(unbind-key "C-x u")
(unbind-key "C-k")
(unbind-key "C-z")
(unbind-key "M-<")
(unbind-key "M->")
(unbind-key "C-z")
(unbind-key "C-p")
(unbind-key "C-n")
(unbind-key "M-j")
(unbind-key "C-a")
(unbind-key "C-e")
(unbind-key "C-j")
(unbind-key "C-o")
(unbind-key "M-a")
(unbind-key "M-e")
(unbind-key "M-g g")
(unbind-key "C-SPC")
(unbind-key "M-t")
(unbind-key "M-y")
(unbind-key "M-v")
(unbind-key "C-v")
(unbind-key "M-f")
(unbind-key "C-f")
(unbind-key "C-b")
(unbind-key "C-d")
(unbind-key "C-x C-c")
(unbind-key "C-M-q")
(unbind-key "C-x C-z")
(unbind-key "C-x f")
(unbind-key "C-s")
(unbind-key "M-s")

;; Bind
(bind-key* "<tab>" (lambda () (interactive) (if (minibufferp) (call-interactively 'minibuffer-complete) (call-interactively 'dabbrev-expand))))
(bind-key* "<backtab>" 'undo)
(bind-key* "M->" 'indent-for-tab-command)
(bind-key* "M-," 'backward-char)
(bind-key* "M-." 'forward-char)
(bind-key* "M-q" 'undo)
(bind-key* "M-a" 'backward-kill-word-without-fucking-up-the-clipboard)
(bind-key* "M-s" 'kill-word-without-fucking-up-the-clipboard)
(bind-key* "M-d" 'kill-whole-line-without-fucking-up-the-clipboard)
(bind-key* "M-z" 'backward-delete-char-untabify)
(bind-key* "M-x" 'delete-char)
(bind-key* "M-i" 'previous-line)
(bind-key* "M-j" 'next-line)
(bind-key* "M-k" 'backward-word)
(bind-key* "M-l" 'forward-word)
(bind-key* "M-o" 'back-to-indentation)
(bind-key* "M-p" 'move-end-of-line)
(bind-key* "M-n" 'isearch-forward)
(bind-key* "M-b" 'isearch-backward)
(bind-key* "M-h" 'scroll-up-command)
(bind-key* "M-u" 'scroll-down-command)
(bind-key* "M-g" 'goto-line)
(bind-key* "M-SPC" 'set-mark-command)
(bind-key* "M-w" (lambda () (interactive) (call-interactively 'simpleclip-copy) (call-interactively 'keyboard-quit)))
(bind-key* "M-e" 'simpleclip-paste)
(bind-key* "M-r" 'simpleclip-cut)
(bind-key* "M-ö" 'recenter-top-bottom)
(bind-key* "M-c" (lambda () (interactive) (if (minibufferp) (call-interactively 'minibuffer-complete-and-exit) (call-interactively 'newline))))
(bind-key* "C-M-q" 'save-buffers-kill-terminal)
(bind-key* "M-§" 'execute-extended-command)
(bind-key* "M--" 'previous-buffer)
(bind-key* "C--" 'next-buffer)
(bind-key* "C-u" 'beginning-of-buffer)
(bind-key* "C-h" 'end-of-buffer)
(bind-key* "C-z" 'downcase-word)
(bind-key* "C-x" 'upcase-word)
(bind-key* "C-c" 'capitalize-word)
(bind-key* "C-M-s" 'save-buffer)
(bind-key* "C-M-w" 'write-file)
(bind-key* "C-M-f" 'find-file)
(bind-key* "C-M-q" 'kill-this-buffer)
(bind-key* "C-M-b" 'switch-to-buffer)
(bind-key* "<backspace>" 'delete-other-windows)
(bind-key* "C-?" 'describe-key)
(bind-key* "<f1>" (lambda () (interactive)
                     (let (frame1 frame2)
                       (setq frame1 (selected-frame))
                       (switch-to-buffer-other-frame (current-buffer))
                       (setq frame2 (selected-frame))
                       (select-frame-set-input-focus frame1)
                       (call-interactively 'previous-buffer)
                       (select-frame-set-input-focus frame2))))
(bind-key* "M-!" 'execute-region-contents-as-shell-command-and-print-output)

(bind-key "M-b" 'isearch-repeat-backward isearch-mode-map)
(bind-key "M-n" 'isearch-repeat-forward isearch-mode-map)
(bind-key "M-c" 'isearch-exit isearch-mode-map)
